### PR TITLE
Don't install ruby-debug on travis-ci.org 

### PR DESCRIPTION
**Pull request by michaelklishin**
It takes forever to compile

### CODE REVIEW

**Comment by danpersa** [comment]
thanks for the tip... but actually travis-ci don't even run my tests...

**Comment by michaelklishin** [comment]
If you explain what do you mean by "does not run your tests", we can help you.

**Comment by danpersa** [comment]
Hello,

I'll try to describe my problem as detailed as possible

The last lines from my last travis build look like this:

105Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
106$ mysql -e 'create database personal_log_test;' >/dev/null
107$ bundle exec rake
108(in /home/vagrant/builds/danpersa/personal-log)
109rake aborted!
110Expected /home/vagrant/builds/danpersa/personal-log/app/models/user.rb to define User
111
112(See full trace by running task with --trace)
113
114Done. Build script exited with: 1

I'm using the next travis.yml configuration file:

rvm:
- 1.9.2
  before_script:
- "mysql -e 'create database personal_log_test;' >/dev/null"

I'm using rspec as a testing framework, maybe I have to "tell" travis to use it instead of the default testing framework...
But the problems seem to be in the user.rb file... I'm not sure how to see all the stacktrace, as the log suggested...

By the way, the ruby-debug gem is installed in the development group... isn't this enough for travis not to include it?

Thank you in advance,
    Dan

**Comment by michaelklishin** [comment]
What do you do to run your tests locally? Your .travis.yml script is missing `script:` and thus travis will run `bundle exec rake`. For Ruby on Rails applications, you typically need to create databases using rake tasks and migrate them.

**Comment by svenfuchs** [comment]
@danpersa the error you have is a rails error message (activesupport dependencies, more specifically) that is not specific to Travis CI.

You might want to try to add `rake --trace` to your .travis.yml file so that you'll get a more informative backtrace about where the error comes from

Also, when you run `bundle exec rake` locally, do you get the same error message? Or will it then execute the tests?

**Comment by danpersa** [comment]
I updated to the last version of rake, and now I don't get initial error... but for now I think travis-ci has some networking problems, it can't fetch the gems:

http://travis-ci.org/#!/danpersa/personal-log

I'll try again later...

If I run `bundle exec rake` on my local machine, it works just fine...

**Comment by michaelklishin** [comment]
Yes, [our hosting provider is having issues today](http://www.hetzner-status.de/en.html)

**Pull request closed without merging**
